/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AESEncryption: typeof import('./src/components/AESEncryption.vue')['default']
    ConuntDown: typeof import('./src/components/ConuntDown.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NavigationBar: typeof import('./src/components/NavigationBar.vue')['default']
    Table2: typeof import('./src/components/Table2.vue')['default']
    TableDraggable: typeof import('./src/components/TableDraggable.vue')['default']
  }
}
